[package]
name = "meshes"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
thiserror = "^2.0"

base64 = { workspace = true }
x25519-dalek = { workspace = true }
