[package]
name = "meshes"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
x25519-dalek = { version = "^2", features = ["static_secrets"] }
base64 = "^0.22"
thiserror = "^2.0"
